---
- name: tests - apply role
  hosts: all
  tags: ghost_tests_apply

  roles:
    - .

  tasks:
    - meta: flush_handlers

    - name: tests - sleep for Ghost startup
      pause:
        seconds: 15
        prompt: "Waiting for Ghost startup..."

    - name: tests - install curl
      apt:
        pkg: curl
        install_recommends: no
        state: present
      sudo: yes

- name: tests - run tests
  hosts: all
  tags: ghost_tests_run

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  tasks:
    - name: tests - check if ghost is listening
      command: curl --silent {{ ghost_config_url }}
      changed_when: false
      ignore_errors: yes
      register: ghost_test_listening

    - name: tests - check why ghost is not listening
      command: node {{ ghost_install_dir }}/index.js
      args:
        chdir: "{{ ghost_install_dir }}"
        env:
          NODE_ENV: production
      changed_when: false
      ignore_errors: yes
      sudo_user: "{{ ghost_user_name }}"
      sudo: yes
      when: ghost_test_listening | failed

    - name: tests - assert that Ghost is listening
      assert:
        that: "{{ ghost_test_listening | success }}"

    - name: tests - check if Nginx is proxying Ghost
      command: curl --silent localhost:{{ ghost_nginx_port }}
      changed_when: false
      ignore_errors: yes
      register: ghost_test_nginx_proxy

    - name: tests - assert that Nginx is proxying Ghost
      assert:
        that: "{{ ghost_test_nginx_proxy | success }}"

