---
- name: install - install Ghost
  npm:
    path: "{{ ghost_install_dir }}"
    production: yes
    state: present
  sudo_user: "{{ ghost_user_name }}"
  sudo: yes

- name: install - add configurations
  template:
    src: config.js.j2
    dest: "{{ ghost_install_dir }}/config.js"
    owner: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    mode: 0644
  notify: ghost - restart service
  sudo: yes

- name: configure database
  local_action: stat path="{{ inventory_dir }}/host_files/{{ inventory_hostname }}/ghost.db"
  register: p

- name: configure Add provided database
  copy:
    src={{ inventory_dir }}/host_files/{{ inventory_hostname }}/ghost.db
    dest=/opt/tinker/shared_files/ghost/content/data/ghost.db
    owner="{{ ghost_user_name }}"
    group="{{ ghost_user_group }}"
    mode=644
  when: p.stat.exists
  sudo: yes

- name: install - add init script
  template:
    src: init.ghost.j2
    dest: /etc/init.d/ghost
    owner: root
    group: root
    mode: 0755
  sudo: yes

- name: install - enable Ghost service
  service:
    name: ghost
    enabled: yes
    state: restarted
  sudo: yes

