---
- name: prepare - install unzip
  apt:
    pkg: unzip
    update_cache: yes
    cache_valid_time: 3600
    state: installed
  become: yes

- name: prepare - fetch Ghost
  get_url:
    url: "{{ ghost_fetch_url }}"
    dest: "{{ ghost_fetch_dir }}/ghost.zip"
    mode: 0644
  when: ghost_repo == "https://github.com/TryGhost/Ghost"

- name: prepare - check if Ghost installation path exists
  stat:
    path: "{{ ghost_repos_path }}"
  register: ghost_check_install_dir

- name: prepare - create Ghost installation path if necessary
  file:
    dest: "{{ ghost_repos_path }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  become: yes
  when: not ghost_check_install_dir.stat.exists

- name: prepare - add Ghost group
  group:
    name: "{{ ghost_user_group }}"
    system: yes
    state: present
  become: yes

- name: prepare - add Ghost user
  user:
    name: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    home: "/home/{{ ghost_user_name }}"
    createhome: yes
    shell: /bin/bash
    system: yes
    state: present
  become: yes

- name: prepare - unzip Ghost
  unarchive:
    src: "{{ ghost_fetch_dir }}/ghost.zip"
    dest: "{{ ghost_install_dir }}"
    owner: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    copy: no
    creates: "{{ ghost_install_dir }}/index.js"
  when: ghost_repo == "https://github.com/TryGhost/Ghost"
  become: yes

- name: Ensure git is installed
  apt: name=git state=present
  when: ghost_repo != "https://github.com/TryGhost/Ghost"
  become: true

- name: prepare - Add the remot host public key
  shell: ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts
  become: yes

- name: prepare - clone Ghost files
  git:
    repo="{{ ghost_repo }}"
    dest="{{ ghost_install_dir }}"
    force=yes
    accept_hostkey=True
    key_file="/home/{{ ghost_user_name }}/.ssh/{{ ghost_repo_ssh_key_name }}"
  when: ghost_repo != "https://github.com/TryGhost/Ghost"
  become: yes

- name: prepare - Make sure user owns folders
  file:
    path: "{{ ghost_install_dir }}"
    owner: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    recurse: yes
    state: directory
  become: yes
