---
- name: prepare - check if Ghost installation path exists
  stat:
    path: "{{ ghost_repos_path }}"
  register: ghost_check_install_dir

- name: prepare - create Ghost installation path if necessary
  file:
    dest: "{{ ghost_repos_path }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  become: yes
  when: not ghost_check_install_dir.stat.exists

- name: prepare - add Ghost group
  group:
    name: "{{ ghost_user_group }}"
    system: yes
    state: present
  become: yes

- name: search for ghost user
  shell: "awk -F: -v v={{ ghost_user_name }} '{if ($1==v) print $1}' /etc/passwd"
  register: command_result

- name: prepare - add Ghost user
  user:
    name: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    home: "/home/{{ ghost_user_name }}"
    createhome: yes
    shell: /bin/bash
    system: yes
    state: present
  become: yes
  when: command_result.stdout == ""

- name: Ensure git is installed
  apt: name=git state=present
  when: ghost_repo != ""
  become: true

- name: prepare - Add the remot host public key
  shell: ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts
  become: yes

- name: prepare - clone Ghost files
  git:
    repo="{{ ghost_repo }}"
    dest="{{ ghost_install_dir }}/{{ ghost_repo | basename }}"
    force=yes
    accept_hostkey=True
    key_file="/home/{{ ghost_user_name }}/.ssh/{{ ghost_repo_ssh_key_name }}"
  when: ghost_repo != ""
  become: yes

- name: prepare - Make sure user owns folders
  file:
    path: "{{ ghost_install_dir }}"
    owner: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    recurse: yes
    state: directory
  when: ghost_repo != ""
  become: yes
